services:
  - type: web
    name: my-spring-boot-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: ${DATABASE_URL}
      - key: SPRING_DATASOURCE_USERNAME
        value: ${DATABASE_USER}
      - key: SPRING_DATASOURCE_PASSWORD
        value: ${DATABASE_PASSWORD}
